import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "1.5rem",
      screens: {
        "2xl": "1280px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['Nunito Sans', 'system-ui', 'sans-serif'],
        display: ['Cormorant Garamond', 'Georgia', 'serif'],
        script: ['Dancing Script', 'cursive'],
        body: ['Nunito Sans', 'system-ui', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        brand: {
          cream: "hsl(var(--brand-cream))",
          "cream-dark": "hsl(var(--brand-cream-dark))",
          terracotta: "hsl(var(--brand-terracotta))",
          "terracotta-light": "hsl(var(--brand-terracotta-light))",
          olive: "hsl(var(--brand-olive))",
          "olive-light": "hsl(var(--brand-olive-light))",
          "olive-dark": "hsl(var(--brand-olive-dark))",
          mustard: "hsl(var(--brand-mustard))",
          "mustard-light": "hsl(var(--brand-mustard-light))",
          berry: "hsl(var(--brand-berry))",
          "berry-dark": "hsl(var(--brand-berry-dark))",
          "berry-light": "hsl(var(--brand-berry-light))",
          brown: "hsl(var(--brand-brown))",
          "brown-light": "hsl(var(--brand-brown-light))",
          "warm-gray": "hsl(var(--brand-warm-gray))",
          kraft: "hsl(var(--brand-kraft))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "1rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
      },
      boxShadow: {
        soft: "var(--shadow-soft)",
        medium: "var(--shadow-medium)",
        lifted: "var(--shadow-lifted)",
        berry: "var(--shadow-berry)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(30px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "slide-up": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "float": {
          "0%": { transform: "translate(0, 0)" },
          "12.5%": { transform: "translate(6px, -4px)" },
          "25%": { transform: "translate(8px, -8px)" },
          "37.5%": { transform: "translate(4px, -12px)" },
          "50%": { transform: "translate(0, -10px)" },
          "62.5%": { transform: "translate(-4px, -8px)" },
          "75%": { transform: "translate(-6px, -4px)" },
          "87.5%": { transform: "translate(-3px, -2px)" },
          "100%": { transform: "translate(0, 0)" },
        },
        "float-delayed": {
          "0%": { transform: "translate(0, 0)" },
          "12.5%": { transform: "translate(-5px, -3px)" },
          "25%": { transform: "translate(-8px, -6px)" },
          "37.5%": { transform: "translate(-6px, -10px)" },
          "50%": { transform: "translate(-2px, -12px)" },
          "62.5%": { transform: "translate(3px, -9px)" },
          "75%": { transform: "translate(5px, -5px)" },
          "87.5%": { transform: "translate(3px, -2px)" },
          "100%": { transform: "translate(0, 0)" },
        },
        "float-slow": {
          "0%": { transform: "translate(0, 0)" },
          "16.6%": { transform: "translate(4px, -6px)" },
          "33.3%": { transform: "translate(0, -10px)" },
          "50%": { transform: "translate(-5px, -8px)" },
          "66.6%": { transform: "translate(-6px, -3px)" },
          "83.3%": { transform: "translate(-2px, 2px)" },
          "100%": { transform: "translate(0, 0)" },
        },
        "scroll": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-out",
        "fade-in-up": "fade-in-up 0.8s ease-out forwards",
        "slide-up": "slide-up 0.5s ease-out",
        "scale-in": "scale-in 0.3s ease-out",
        "float": "float 25s ease-in-out infinite",
        "float-delayed": "float-delayed 30s ease-in-out infinite 5s",
        "float-slow": "float-slow 35s ease-in-out infinite 10s",
        "scroll": "scroll 20s linear infinite",
        "marquee": "scroll 30s linear infinite",
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
